# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
before_install: 
  - cd Example
  - pod install
script:
- xctool test -workspace FFCPieChart.xcworkspace -scheme FFCPieChart -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
